# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54aaa823a2021b0bcacd1602c9dc26cd61fbc10663e2a3419864d669a5f5fcab9e9862e5f14d0f187805397529f34a8a289438c3c37e9651aedafdf9321b8c68

test:
  secret_key_base: 6ceb9f43194329c5f228abd336eae600fed19115428fa4f3ca3711ea068a362adfd86dd6212731871f426a04bf62f21d73ad2da8ceb8a747b4df7f2ee818bbfd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
